### ISSUE TITLE
Parsing fails on Chinese/Japanese/... Windows installations

### ISSUE THREAD

**Issue by av930** [Bertware/wlan10#4]
Is it working? Please upload manual here not http://bertware.net/set-windows-network-priority-with-wlan10/

==issue report===
1. download app 
2. run in windows 10
3. nothing is listed. 
![image](https://cloud.githubusercontent.com/assets/990793/20514142/b744bc86-b0cd-11e6-89be-9bc962aed9f7.png)

**Comment by Bertware** [comment]
All saved networks should show up instantly after opening the application. WiFi signals in range, which aren't saved yet to your computer won't show up. (so you should only expect networks which are already stored).

If you did not get any results, and you didn't get any errors, this likely means there simply aren't any saved networks. 

Can you open a command prompt (cmd) window, run this output, and put it here? You can blur out or change network names of you like.

    Netsh wlan sh profiles

**Comment by av930** [comment]
here is result. Wlan10 vs netsh command screenshot
![image](https://cloud.githubusercontent.com/assets/990793/20523534/e33041f0-b0f8-11e6-9b21-78949139f9c8.png)

**Comment by Bertware** [comment]
This explains a lot ;) The parser doesn't detect the networks since everything's chinese (or a similar language). 
The parser expects everything in English, as all windows versions, no matter the language, seem to have their command prompt in English (This has been tested on Dutch, German, Swedish, ...).
I'll see if I can force the netshell output to English.

**Comment by av930** [comment]
Ok I got it. It is Korean. 
How about classify by colon(:) not the prefix-language ?
I think it would be enough.
I really like to use your tool.

**Comment by Bertware** [comment]
A possible solution for this would be to dump netshell, and switch to the native Wifi API:
https://msdn.microsoft.com/en-us/library/ms706274(v=vs.85).aspx

It's more complex than splitting on the colon, since there are more queries required for further details about the network. Those queries can't be parsed in any other way than using the field version.

I'll see if I can look into the Wlan API, though it's rather complex and I'm only doing this in my free time.

**Comment by av930** [comment]
Basically I agree your decision. however I think this problem is only dependent on locale (language).
I'd rather recommend to use easier way classifying colon and post-fix network SSID value(this is available only in English).
Anyway thanks in advance.

**Comment by Bertware** [comment]
Another required command is "netshell wlan show profile <name>", in your case for example "netshell wlan show profile iptime". The only way to parse this command, which contains more details about a network, is by using the field names, which should be in English. So either the output needs to be forced to English, or an API should be used. The use of an API is the better solution here (I did not know of this API before I coded this, if I knew about it I would have used it already)

**Comment by av930** [comment]
With "chcp  437" command, I changed my default language to English, but still I have a problem. 
As you said. there are more subtle issue about this. 
![image](https://cloud.githubusercontent.com/assets/990793/20525764/4689793c-b104-11e6-9fbe-31ab775decd8.png)

**Comment by Bertware** [comment]
About that command: 

    Change the active console Code Page. The default code page is determined by the Windows Locale. 

This means the program still gets the korean output. As I said, using an API instead of parsing console output is the only solution here

**Comment by av930** [comment]
OK I got it.

**Comment by afit** [comment]
I've just submitted pull request #8 which fixes this for Unicode without the need to use the API.

**Comment by Bertware** [comment]
Thanks for your contribution! PR has been merged
